### ISSUE TITLE
Cenário 1 parcialmente (não para a máquina ao abrir porta, risco a criança)

### ISSUE THREAD

**Issue by eduardomarossi** [Veronur/Aps2Embarcados#12]

**Comment by Veronur** [comment]
Mas du, a maquina sequer abre se estiver ligada, não abordei esse caso pois ele não tem como ocorrer. Enquanto a maquina esta ligada se você aperta o botão pra abrir a porta ele não faz nada.

**Comment by eduardomarossi** [comment]
Expliquei na sala o motivo.

No entanto, para efeitos de rubrica, não vamos exigir esse requisito.
